name: .NET 5 Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '#skip_ci')"
     
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Fetch
      run: git fetch --unshallow
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: install versioning tool
      run: dotnet tool install --tool-path . nbgv
    - name: Install dependencies
      run: dotnet restore
    - name: Build Loader
      run: dotnet build --configuration Release --no-restore PlanetaryDocsLoader/PlanetaryDocsLoader.csproj
    - name: Build Blazor Server App
      run: dotnet build --configuration Release --no-restore PlanetaryDocs/PlanetaryDocs.csproj
  
